---

- name: "Lookup java path"
  command: "{{ script_paths.env_utility_script }}/env_info_helper.py real_path java"
  register: tmp_java_path

- name: "Set java path fact"
  set_fact:
    java_path: "{{ tmp_java_path.stdout | regex_replace('/jre/bin/.*', '') }}"


- name: "Create profile script for java paths"
  template: 
    src: templates/java.sh
    dest: /etc/profile.d/java.sh
    mode: 0644


