
- name: "Create user groups"
  group:
    name: "{{ item.group }}"
    state: present
  with_items:
    - "{{ users_groups_map }}"


- name: "Create users"
  user:
    name: "{{ item.username }}"
    group: "{{ item.group }}"
    home: "{{ item.homedir }}"
    state: present
  with_items:
    - "{{ users_groups_map }}"


- name: "Create bin directory in jenkins home"
  file:
    path: "{{ jenkins_home }}/bin"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755



