
- name: "Create user groups"
  group:
    name: "{{ item.group }}"
    state: present
  with_items:
    - "{{ users_groups_map }}"


- name: "Create users"
  user:
    name: "{{ item.username }}"
    group: "{{ item.group }}"
    home: "{{ item.homedir }}"
    state: present
  with_items:
    - "{{ users_groups_map }}"


# - name: "Create user groups"
#   group:
#     name: "{{ item.2 }}"
#     state: present
#   with_items:
#     - "{{ users_groups }}"
# 
# 
# - name: "Create users"
#   user:
#     name: "{{ item.1 }}"
#     group: "{{ item.2 }}"
#     home: "{{ item.3 }}"
#     state: present
#   with_items:
#     - "{{ users_groups }}"
# 
